SELECT COUNT(PKG.UOMDESCR)
FROM BAS_SKU SKU INNER JOIN BAS_PACKAGE_DETAILS PKG
ON(SKU.OrganizationId=PKG.OrganizationId AND SKU.customerId=PKG.customerId 
AND SKU.PACKID=PKG.PACKID AND SKU.customerId='PAPAYA') WHERE  SKU.SKU='050202428' AND PKG.UOMDESCR='PCS'