select DOC_WAVE_HEADER.WAVENO 
  From DOC_WAVE_HEADER DOC_WAVE_HEADER
 Where DOC_WAVE_HEADER.WAVESTATUS <> '99'
   and DOC_WAVE_HEADER.WAVESTATUS > '00'
   and DOC_WAVE_HEADER.WAVESTATUS <> '63'
   and DOC_WAVE_HEADER.WAVESTATUS <> '60'
   and DOC_WAVE_HEADER.RELEASESTATUS <> 'N'
 AND DOC_WAVE_HEADER.WAVENO =
'WAVE22072800289'
   AND EXISTS
 (SELECT 1
          FROM DOC_WAVE_DETAILS DOC_WAVE_DETAILS
         INNER JOIN TSK_TASKLISTS TSK_TASKLISTS
            ON DOC_WAVE_DETAILS.ORDERNO = TSK_TASKLISTS.DOCNO
           AND TSK_TASKLISTS.TASKPROCESS <> '99'
         INNER JOIN BAS_LOCATION BAS_LOCATION
            ON TSK_TASKLISTS.FMLOCATION = BAS_LOCATION.LOCATIONID
         INNER JOIN BAS_ZONE BAS_ZONE
            ON BAS_LOCATION.ZONEID = BAS_ZONE.ZONEID
         INNER JOIN BAS_ZONEGROUP BAS_ZONEGROUP
            ON BAS_ZONE.ZONEGROUP = BAS_ZONEGROUP.ZONEGROUP
         WHERE DOC_WAVE_HEADER.WAVENO = DOC_WAVE_DETAILS.WAVENO
           AND TSK_TASKLISTS.TASKTYPE = 'PK'
           AND (TSK_TASKLISTS.FMLOCATION >=
               '@TXT_LOCATIONIDFM_1#ALLOW_EMPTY#@')
           AND (TSK_TASKLISTS.FMLOCATION <=
               '@TXT_LOCATIONIDTO_1#ALLOW_EMPTY#@')
           AND (TSK_TASKLISTS.PLANTOID = '@TXT_LABELNO_1#ALLOW_EMPTY#@')
           AND (BAS_ZONE.ZONEID = '@TXT_ZONE_1#ALLOW_EMPTY#@')
           AND (BAS_LOCATION.LOCGROUP1 = '@TXT_LOCGROUP1_1#ALLOW_EMPTY#@')
           AND (BAS_LOCATION.LOCGROUP2 = '@TXT_LOCGROUP2_1#ALLOW_EMPTY#@')
           AND (BAS_LOCATION.TERMINALNO1 = '@TXT_PORTNO_1#ALLOW_EMPTY#@')
           AND (BAS_LOCATION.WORKINGAREA =
               '@TXT_WORKINGAREA_1#ALLOW_EMPTY#@'))
 ORDER BY DOC_WAVE_HEADER.WAVENO DESC ;



-- SELECT RELEASESTATUS FROM DOC_WAVE_HEADER dwh WHERE dwh.waveNo='WAVE22072800038';


-- SELECT * FROM TSK_TASKLISTS WHERE docNo IN (SELECT docNo FROM DOC_WAVE_DETAILS  dwh WHERE dwh.waveNo='WAVE22072800038') AND warehouseId='WHPGD01' AND taskType='P