-- DELETE FROM WMS_FTEST.SYS_DEV_RF_FORM_UDF WHERE functionid = 'WRF_H5INB01006'
  SELECT * FROM WMS_FTEST.SYS_DEV_RF_FORM_UDF  WHERE functionid = 'WRF_H5INB01006';
      DELETE FROM WMS_FTEST.SYS_DEV_RF_FORM  WHERE functionid = 'WRF_H5INB01006'