USE wms_cml;

SELECT * FROM BAS_SKU  WHERE customerId='API' AND sku='10000000001';

SELECT * FROM BAS_SKU_ACCESSORY  WHERE customerId='API';

SELECT * FROM BAS_SKU_CONFLICT  WHERE customerId='API';


SELECT * FROM BAS_SKU_CONSIGNEE  WHERE customerId='API';

SELECT * FROM BAS_SKU_MULTIPACKAGE  WHERE customerId='API';

SELECT * FROM BAS_SKU_MULTIWAREHOUSE  WHERE customerId='API' AND sku='10000000001';

SELECT * FROM BAS_SKU_ORDERRULES  WHERE customerId='API';

SELECT * FROM BAS_SKU_PHARMAPPROVALNO  WHERE customerId='API';

SELECT * FROM BAS_SKU_PHARMGMPCERT  WHERE customerId='API';

SELECT * FROM BAS_SKU_PUTAWAYZONE  WHERE customerId='API';

SELECT * FROM BAS_SKU_QCITEM  WHERE customerId='API';

SELECT * FROM BAS_SKU_SUBSTITUDE  WHERE customerId='API';

SELECT * FROM BAS_SKU_SUPPLIER  WHERE customerId='API';

SELECT * FROM BAS_SKU_TEMPLATE  WHERE customerId='API';

SELECT * FROM BAS_SKU_UDF  WHERE customerId='API';



-- DELETE FROM BAS_SKU  WHERE customerId='API';




-- UPDATE BAS_SKU SET softAllocationRule = 'STANDARD', allocationRule = 'STANDARD' WHERE organizationId = 'OJV_CML' AND customerId = 'API';



-- UPDATE BAS_SKU_MULTIWAREHOUSE SET reportUom = 'EA', tariffMasterId = 'BIL00055' WHERE organizationId = 'OJV_CML' AND customerId = 'API';


  SELECT COUNT(1) FROM DOC_ASN_DETAILS WHERE warehouseId='CBT02' AND customerId='API' AND asnNo='ASNAPI211106002'


 