SELECT COUNT(*) FROM wms_cml.INV_LOT_LOC_ID_300622;

SELECT COUNT(*) FROM wms_cml.INV_LOT_LOC_ID_290622;

TRUNCATE TABLE INV_LOT_LOC_ID_290622;

CREATE TABLE INV_LOT_LOC_ID_290622 AS SELECT * FROM INV_LOT_LOC_ID illi WHERE 1=2;


CREATE TABLE wms_cml.Z_InventoryBalance_XX AS SELECT * FROM Z_InventoryBalance zib WHERE 1=2;


SELECT * FROM wms_cml.Z_InventoryBalance_XX;
