  SELECT 
    DOC_ASN_HEADER.ASNTYPE,
    DOC_ASN_DETAILS.ASNNO AS HIDE_ASNNO_2,
    DOC_ASN_DETAILS.ASNLINENO AS HIDE_ASNLINENO,
    DOC_ASN_DETAILS.CUSTOMERID AS HIDE_CUSTOMERID,
    DOC_ASN_DETAILS.SKU HIDE_SKU,
    DOC_ASN_DETAILS.PACKID AS WXT_PACKID_2,
    DOC_ASN_DETAILS.PACKUOM AS WXT_UOM_2,
    DOC_ASN_DETAILS.EXPECTEDQTY AS WXT_TQTY_2,
    DOC_ASN_DETAILS.RECEIVEDQTY AS WXT_RQTY_2, 
    DOC_ASN_DETAILS.EXPECTEDQTY_EACH,
    DOC_ASN_DETAILS.RECEIVEDQTY_EACH,
    BAS_SKU.PACKID AS DEFAULTPACKID,
    BAS_SKU.DEFAULTRECEIVINGUOM AS DEFAULTRECEIVINGUOM,
    BAS_SKU.SKUDESCR1 AS SKUDESCRC,
    BAS_SKU.SKUDESCR2 AS SKUDESCRE,
   
DOC_ASN_DETAILS.EXPECTEDQTY_EACH AS HIDE_EXPECTEDQTY_EACH,
    DOC_ASN_DETAILS.RECEIVEDQTY_EACH AS HIDE_RECEIVEDQTY_EACH
  FROM
    DOC_ASN_DETAILS 
    LEFT JOIN DOC_ASN_HEADER 
      ON DOC_ASN_HEADER.ASNNO = DOC_ASN_DETAILS.ASNNO 
    LEFT JOIN BAS_SKU 
      ON DOC_ASN_DETAILS.CUSTOMERID = BAS_SKU.CUSTOMERID 
      AND DOC_ASN_DETAILS.SKU = BAS_SKU.SKU 
    LEFT JOIN BAS_CUSTOMER 
      ON DOC_ASN_DETAILS.CUSTOMERID = BAS_CUSTOMER.CUSTOMERID 
      AND BAS_CUSTOMER.CUSTOMERTYPE = 'OW' 
    LEFT JOIN BAS_PACKAGE 
      ON DOC_ASN_DETAILS.CUSTOMERID = BAS_PACKAGE.CUSTOMERID 
      AND DOC_ASN_DETAILS.PACKID = BAS_PACKAGE.PACKID 
    LEFT JOIN BAS_PACKAGE_DETAILS VIEW_UOM_1 
      ON DOC_ASN_DETAILS.CUSTOMERID = VIEW_UOM_1.CUSTOMERID 
      AND DOC_ASN_DETAILS.PACKUOM = VIEW_UOM_1.PACKUOM 
      AND DOC_ASN_DETAILS.PACKID = VIEW_UOM_1.PACKID 
    LEFT JOIN BAS_PACKAGE_DETAILS VIEW_UOM_2 
      ON BAS_SKU.CUSTOMERID = VIEW_UOM_2.CUSTOMERID 
      AND BAS_SKU.DEFAULTRECEIVINGUOM = VIEW_UOM_2.PACKUOM 
      AND BAS_SKU.PACKID = VIEW_UOM_2.PACKID 
  WHERE DOC_ASN_DETAILS.ASNNO = 'PPG_ASNNO00000000082'
  -- AND DOC_ASN_DETAILS.SKU = '00445303'   
order by DOC_ASN_DETAILS.linestatus 
limit 0,1;

SELECT bpd.packUom,bpd.qty 
FROM BAS_PACKAGE_DETAILS bpd WHERE bpd.packId='1/0/1/144-18X18X23';



SELECT 
bpd.packUom ,
bpd.uomDescr,
bpd.qty
from BAS_SKU bs 
right join BAS_PACKAGE_DETAILS bpd 
on bs.packId = bpd.packId 
and bs.customerId = bpd.customerId 
where bs.organizationId = 'OJV_CML'
and bs.sku = '00445303'
and bs.customerId = 'PPG'
and bpd.qty > 0