--
-- Script was generated by Devart dbForge Studio for MySQL, Version 10.0.150.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 5/16/2025 5:17:39 PM
-- Server version: 8.0.42
-- Please backup your database before running this script
--


SET NAMES 'utf8';

GRANT EXECUTE,ALTER ROUTINE ON PROCEDURE wms_cml.CML_COUNT_STORAGE_DAYS TO 'it.ari'@'%';
                                                                                  
FLUSH PRIVILEGES;



USE wms_cml;
DELIMITER //

CREATE PROCEDURE `drop_procedure`(IN p_procedure_name VARCHAR(255))
SQL SECURITY DEFINER
BEGIN
    IF p_procedure_name IN ('CML_COUNT_STORAGE_DAYS','CML_COUNT_RENT_PALLET_DAYS') THEN
        SET @sql = CONCAT('DROP PROCEDURE IF EXISTS `wms_cml`.`', p_procedure_name, '`');
        PREPARE stmt FROM @sql;
        EXECUTE stmt;
        DEALLOCATE PREPARE stmt;
        SELECT CONCAT('Procedure ', p_procedure_name, ' dropped successfully.') AS message;
    ELSE
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'You are not allowed to drop this specific procedure.';
    END IF;
END //

DELIMITER ;