SELECT
  BAS_CUSTOMER.customerId,
  BAS_CUSTOMER.customerType,
  BAS_CUSTOMER.customerDescr1,
  BAS_CUSTOMER.udf02,
  BIL_CRM_HEADER.CustomerId,
  BIL_CRM_HEADER.OpportunityId,
  BIL_TARIFF_MASTER.tariffMasterId,
  BIL_CRM_HEADER.warehouseId,
  BIL_TARIFF_HEADER.tariffId
FROM BIL_CRM_HEADER
  INNER JOIN BAS_CUSTOMER
    ON BIL_CRM_HEADER.CustomerId = BAS_CUSTOMER.udf02
    AND BAS_CUSTOMER.customerType = 'OW'
  INNER JOIN BIL_TARIFF_MASTER
    ON BIL_TARIFF_MASTER.customerId = BAS_CUSTOMER.customerId
  INNER JOIN BIL_TARIFF_HEADER
    ON BIL_TARIFF_MASTER.tariffMasterId = BIL_TARIFF_HEADER.tariffMasterId
WHERE 1=1
-- AND  BIL_CRM_HEADER.OpportunityId = '0062w00000NguxNAAR'
AND BIL_TARIFF_HEADER.effectiveFrom <= DATE_FORMAT(CURDATE(), '%Y-%m-%d')
AND BIL_TARIFF_HEADER.effectiveTo >= DATE_FORMAT(CURDATE(), '%Y-%m-%d')